# Generated by Django 4.2.7 on 2023-11-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_lang', models.CharField(max_length=250)),
                ('audio', models.FileField(upload_to='lesson/dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_lesson', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=300)),
                ('price', models.PositiveIntegerField(default=100)),
                ('dialog_audio', models.FileField(upload_to='lesson/dialog')),
                ('dialog_audio_ru', models.FileField(null=True, upload_to='lesson/dialog')),
                ('dialog_audio_uz', models.FileField(null=True, upload_to='lesson/dialog')),
                ('dialog_audio_en', models.FileField(null=True, upload_to='lesson/dialog')),
                ('dialog_text', models.TextField()),
                ('dialog_text_ru', models.TextField(null=True)),
                ('dialog_text_uz', models.TextField(null=True)),
                ('dialog_text_en', models.TextField(null=True)),
                ('phrase_audio', models.FileField(upload_to='lesson/phrase')),
                ('phrase_audio_ru', models.FileField(null=True, upload_to='lesson/phrase')),
                ('phrase_audio_uz', models.FileField(null=True, upload_to='lesson/phrase')),
                ('phrase_audio_en', models.FileField(null=True, upload_to='lesson/phrase')),
                ('phrase_text', models.TextField()),
                ('phrase_text_ru', models.TextField(null=True)),
                ('phrase_text_uz', models.TextField(null=True)),
                ('phrase_text_en', models.TextField(null=True)),
                ('dictionary_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_ru', models.CharField(max_length=250, null=True)),
                ('name_uz', models.CharField(max_length=250, null=True)),
                ('name_en', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_view', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_ru', models.CharField(max_length=120, null=True)),
                ('name_uz', models.CharField(max_length=120, null=True)),
                ('name_en', models.CharField(max_length=120, null=True)),
                ('image', models.ImageField(upload_to='subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='course.subject')),
            ],
        ),
    ]
